services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=drawapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"

  frontend-backend:
    build: 
      context: .
      dockerfile: docker-dev/Dockerfile.frontend-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - ws-backend
    environment:
      - NEXTAUTH_SECRET=435453454543534553545
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://root:root@db:5432/drawapp
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - REDIS_PASS=

  ws-backend:
    build: 
      context: .
      dockerfile: docker-dev/Dockerfile.ws
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6380
      - SOCKET_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - DATABASE_URL=postgresql://root:root@db:5432/drawapp
  
  general-services:
    build: 
      context: .
      dockerfile: docker-dev/Dockerfile.generalservice
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/drawapp

  shape-services:
    build: 
      context: .
      dockerfile: docker-dev/Dockerfile.shapeservice
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - DATABASE_URL=postgresql://root:root@db:5432/drawapp

  email-services:
    build: 
      context: .
      dockerfile: docker-dev/Dockerfile.emailservice
    depends_on:
      - db
      - redis
    environment:
      - JWT_EMAIL_SECRET='sdlklfhsklfhkldsfsdf'
      - EMAIL_ADDRESS=#youremailaddress
      - EMAIL_PASSWORD=#youremailpassword
      - CLIENT_URL=http://localhost:3000/
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - DATABASE_URL=postgresql://root:root@db:5432/drawapp

volumes:
  postgres-data: