FROM node:23.8.0-alpine

ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASS

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ../package.json ../pnpm-lock.yaml ../pnpm-workspace.yaml ../turbo.json ./
COPY ../apps/frontend/package.json ./apps/frontend/package.json
COPY ../apps/frontend/package-lock.json ./apps/frontend/package-lock.json
COPY ../packages/common/package.json ./packages/common/package.json
COPY ../packages/cache/package.json ./packages/cache/package.json
COPY ../packages/typescript-config/package.json ./packages/typescript-config/package.json
COPY ../packages/backend-common/package.json ./packages/backend-common/package.json
COPY ../packages/db/package.json ./packages/db/package.json
COPY ../packages/email/package.json ./packages/email/package.json
COPY ../packages/eslint-config/package.json ./packages/eslint-config/package.json
COPY ../packages/ui/package.json ./packages/ui/package.json

RUN pnpm install

COPY ../packages ./packages
COPY ../apps/frontend ./apps/frontend

RUN pnpm run db:generate
RUN pnpm build

CMD ["sh", "-c", "pnpm run db:migrate && pnpm run start:web"]