export const HTTP_BACKEND = "http://localhost:5000"
export const JOIN_ROOM="join_room"
export const LEAVE_ROOM="leave_room"
export const WS_URL = `ws://localhost:8000`
export const SHAPE = "SHAPE"
export const DRAW_SHAPE = "DRAW_SHAPE"
export const ERASE = "ERASE"
export const OFF_COLLABORATION = "OFF_COLLABORATION"
export const FULL = "FULL"
export const SIGNUP = 'SIGNUP'
export const FORGOTPASSWORD = 'FORGOTPASSWORD'
export const SIGNIN = 'SIGNIN'
export const RESETPASSWORD = 'RESETPASSWORD'
export const EMAIL_QUEUE = 'email_queue'
export const STOP_COLLAB='stop_collaboration'